import React from 'react';

export const C = {
  bg: '#f8fafc',
  surface: '#ffffff',
  card: '#f4f6f8',
  ind: '#3b5bdb',
  indL: '#5c7cfa',
  indUL: '#dbe4ff',
  green: '#10b981',
  amber: '#f59e0b',
  red: '#ef4444',
  t1: '#0f172a',
  t2: '#475569',
  t3: '#64748b',
  t4: '#94a3b8',
  bdr: '#e2e8f0',
  mono: "'JetBrains Mono', ui-monospace, monospace",
  sans: "'Inter', system-ui, sans-serif",
};

interface ShellProps {
  children: React.ReactNode;
  onNavigate: (route: string) => void;
  currentRoute: string;
}

const NAV = [
  { id: 'home', label: 'Home' },
  { id: 'customer-maint', label: 'Customer Maint' },
  { id: 'customer-orders', label: 'Orders' },
  { id: 'customer-list', label: 'Customer List' },
  { id: 'order-report', label: 'Order Report' },
  { id: 'update-credit', label: 'Credit Update' },
  { id: 'roi', label: 'ROI' },
  { id: 'mapping', label: 'ABL → Modern' },
];

export function Shell({ children, onNavigate, currentRoute }: ShellProps) {
  return (
    <div style={{ fontFamily: C.sans, background: C.bg, minHeight: '100vh', color: C.t1 }}>
      {/* Header */}
      <header style={{
        background: 'white',
        borderBottom: `1px solid ${C.bdr}`,
        padding: '14px 32px',
        display: 'flex', alignItems: 'center', gap: 16,
        position: 'sticky', top: 0, zIndex: 10,
        boxShadow: '0 1px 2px rgba(0,0,0,0.04)',
      }}>
        <a href="#home" onClick={e => { e.preventDefault(); onNavigate('home'); }} style={{
          display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none', color: 'inherit',
        }}>
          <div style={{
            width: 34, height: 34, borderRadius: 8,
            background: `linear-gradient(135deg, ${C.ind}, ${C.indL})`,
            color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontWeight: 800, fontSize: 13, fontFamily: C.mono, letterSpacing: '0.05em',
          }}>PA</div>
          <div>
            <div style={{ fontSize: 15, fontWeight: 700, letterSpacing: '-0.01em' }}>Progress Agent</div>
            <div style={{ fontSize: 11, color: C.t3 }}>Sports2000 modernized</div>
          </div>
        </a>

        <nav style={{ display: 'flex', gap: 3, marginLeft: 20, flex: 1, flexWrap: 'wrap' }}>
          {NAV.slice(1).map(n => (
            <a
              key={n.id}
              href={`#${n.id}`}
              onClick={e => { e.preventDefault(); onNavigate(n.id); }}
              style={{
                fontSize: 13, fontWeight: 500,
                padding: '7px 12px', borderRadius: 6,
                color: currentRoute === n.id ? C.ind : C.t2,
                background: currentRoute === n.id ? C.indUL : 'transparent',
                textDecoration: 'none',
                transition: 'all 0.12s',
              }}
            >{n.label}</a>
          ))}
        </nav>

        <a
          href="https://github.com/anupsahoo/progress-agent"
          target="_blank"
          rel="noopener noreferrer"
          style={{
            fontSize: 12, fontWeight: 600, color: C.t2,
            padding: '6px 12px', borderRadius: 6,
            border: `1px solid ${C.bdr}`,
            textDecoration: 'none',
          }}
        >View on GitHub ↗</a>
      </header>

      {/* Main */}
      <main style={{ maxWidth: 1200, margin: '0 auto', padding: '32px' }}>
        {children}
      </main>

      <footer style={{
        textAlign: 'center', padding: '24px', color: C.t4, fontSize: 12, borderTop: `1px solid ${C.bdr}`,
        background: 'white', marginTop: 60,
      }}>
        Generated by <a href="https://github.com/anupsahoo/flowpilot-ai" style={{ color: C.ind, fontWeight: 600 }}>FlowPilot AI</a> &middot; Progress OpenEdge sports2000 demo
      </footer>
    </div>
  );
}

/** Before/After side-by-side comparison block. */
export function BeforeAfter({ beforeLabel = 'Before — Progress ABL terminal', afterLabel = 'After — Modern React UI', beforeContent, children }: {
  beforeLabel?: string;
  afterLabel?: string;
  beforeContent: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.4fr', gap: 20, marginBottom: 32 }}>
      <div style={{
        background: '#0f172a', color: '#e2e8f0',
        borderRadius: 12, padding: 18,
        fontFamily: C.mono, fontSize: 12, lineHeight: 1.6,
      }}>
        <div style={{
          fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em',
          color: '#94a3b8', marginBottom: 10,
        }}>
          {beforeLabel}
        </div>
        <pre style={{ margin: 0, whiteSpace: 'pre', overflow: 'auto' }}>{beforeContent}</pre>
      </div>
      <div style={{
        background: 'white', borderRadius: 12, padding: 20,
        border: `1px solid ${C.bdr}`, boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
      }}>
        <div style={{
          fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em',
          color: C.green, marginBottom: 10,
        }}>
          {afterLabel}
        </div>
        {children}
      </div>
    </div>
  );
}

export function PageHeader({ title, subtitle, source }: { title: string; subtitle?: string; source?: string }) {
  return (
    <div style={{ marginBottom: 24 }}>
      {source && (
        <div style={{
          fontSize: 10, fontWeight: 700, color: C.t3, fontFamily: C.mono,
          textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6,
        }}>
          Modernized from {source}
        </div>
      )}
      <h1 style={{ fontSize: 28, fontWeight: 700, letterSpacing: '-0.02em', margin: 0, color: C.t1 }}>
        {title}
      </h1>
      {subtitle && (
        <p style={{ fontSize: 14, color: C.t3, marginTop: 6, maxWidth: 640 }}>
          {subtitle}
        </p>
      )}
    </div>
  );
}
