import React from 'react';

const modules: { name: string; slug: string; path: string }[] = [
  { name: 'CustomerMaint', slug: 'customermaint', path: 'src/components/CustomerMaint.tsx' },
  { name: 'Shell', slug: 'shell', path: 'src/components/Shell.tsx' }
];

export default function Home() {
  return (
    <div style={{ fontFamily: 'Inter, system-ui, sans-serif', minHeight: '100vh', background: 'linear-gradient(135deg, #f0f4ff 0%, #fff 100%)' }}>
      <header style={{ padding: '40px 48px', borderBottom: '1px solid #e5e7eb', background: 'white' }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ width: 44, height: 44, borderRadius: 10, background: 'linear-gradient(135deg, #3b5bdb, #5c7cfa)', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, letterSpacing: '0.05em' }}>PA</div>
            <div>
              <h1 style={{ fontSize: 26, fontWeight: 700, color: '#1a1b1e', margin: 0 }}>Progress Agent</h1>
              <p style={{ fontSize: 13, color: '#6b7280', marginTop: 3 }}>Modernized Progress OpenEdge programs — live</p>
            </div>
          </div>
        </div>
      </header>
      <main style={{ padding: '48px', maxWidth: 1000, margin: '0 auto' }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: '#6b7280', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 14 }}>
          Modernized Modules ({modules.length})
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 16 }}>
          {modules.map(m => (
            <a key={m.slug} href={`#/${m.slug}`} style={{
              display: 'block', padding: 20, borderRadius: 12, background: 'white',
              border: '1px solid #e5e7eb', textDecoration: 'none', color: '#1a1b1e',
              boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
            }}>
              <div style={{ fontSize: 11, color: '#3b5bdb', fontFamily: 'monospace', fontWeight: 700, marginBottom: 6, textTransform: 'uppercase' }}>
                {m.path}
              </div>
              <div style={{ fontSize: 16, fontWeight: 700 }}>{m.name}</div>
              <div style={{ fontSize: 12, color: '#6b7280', marginTop: 6 }}>
                Open modernized screen →
              </div>
            </a>
          ))}
        </div>
        {modules.length === 0 && (
          <div style={{ padding: 60, textAlign: 'center', color: '#6b7280', border: '1px dashed #e5e7eb', borderRadius: 12 }}>
            No modules yet. FlowPilot AI will populate this list as it generates modernized components.
          </div>
        )}
      </main>
      <footer style={{ padding: '30px 48px', textAlign: 'center', color: '#9ca3af', fontSize: 12 }}>
        Generated by FlowPilot AI
      </footer>
    </div>
  );
}
